app:
    common:
        bootstrap.servers: ${ARCHER_BOOTSTRAP_SERVERS_TEST}
    application:
        schema.registry.url: ${ARCHER_SCHEMA_REGISTRY_URL}
        replication.factor: 1
    consumer:
        group.id: local-test-group
        client.id: $UUID
        auto.offset.reset: earliest
    producer:
        acks: all
        retries: 1
    streams:
        application.server: localhost:8080
        application.name: test
        application.id: local-test-group
        auto.offset.reset: earliest
        commit.interval.ms: 500
        replication.factor: 1
        group.id: local-test-group
    topicName: test-gateway
