app:
    common:
        bootstrap.servers: ${ARCHER_BOOTSTRAP_SERVERS:PLAINTEXT://localhost:9092}
    application:
        schema.registry.url: ${ARCHER_SCHEMA_REGISTRY_URL:http://localhost:8081}
        host.port: 8080
    streams:
        application.server: ${ARCHER_APPLICATION_SERVER:localhost:8080}
        application.name: ${ARCHER_APPLICATION_NAME:lib_ddd_example}
    ksql:
        ksql.statestore.suffix: _store
        ksql.sink.partitions: ${ARCHER_PARTITIONS:3}
        ksql.sink.replicas: ${ARCHER_REPLICATION_FACTOR:1}
        commit.interval.ms: 500
        auto.offset.reset: earliest
    dataflow:
        client.id: $UUID
        max.poll.interval.ms: 300000
        max.poll.records: 500
        session.timeout.ms: 10000
        state.dir: /tmp/kafka-streams-#client.id#
