app:
    common:
        bootstrap.servers: ${ARCHER_BOOTSTRAP_SERVERS}
    application:
        schema.registry.url: ${ARCHER_SCHEMA_REGISTRY_URL}
        replication.factor: ${ARCHER_REPLICATION_FACTOR:1}
    consumer:
        group.id: ${ARCHER_CONSUMER_GROUP_ID}
        client.id: $UUID
        auto.offset.reset: ${ARCHER_AUTO_OFFSET_RESET:earliest}
    producer:
        acks: ${ARCHER_PRODUCER_ACKS:all}
        retries: ${ARCHER_PRODUCER_RETRIES:1}
    streams:
        application.server: ${ARCHER_APPLICATION_SERVER}
        application.name: ${ARCHER_APPLICATION_NAME}
        auto.offset.reset: ${ARCHER_AUTO_OFFSET_RESET:earliest}
        commit.interval.ms: ${ARCHER_COMMIT_INTERVAL_MS:500}
        replication.factor: ${ARCHER_REPLICATION_FACTOR:1}
