app:
    common:
        bootstrap.servers: ${ARCHER_BOOTSTRAP_SERVERS}
    applicationProperties:
        schema.registry.url: ${ARCHER_SCHEMA_REGISTRY_URL}
        replication.factor: ${ARCHER_REPLICATION_FACTOR:1}
    consumerProperties:
        group.id: ${ARCHER_CONSUMER_GROUP_ID:local-gateway-enrichment-group}
        client.id: $UUID
        auto.offset.reset: ${ARCHER_AUTO_OFFSET_RESET:earliest}
    producerProperties:
        acks: ${ARCHER_PRODUCER_ACKS:all}
        retries: ${ARCHER_PRODUCER_RETRIES:1}
    streamsProperties:
        application.server: ${ARCHER_APPLICATION_SERVER}
        application.name: ${ARCHER_APPLICATION_NAME:kst-archer-gateway}
        auto.offset.reset: ${ARCHER_AUTO_OFFSET_RESET:earliest}
        commit.interval.ms: ${ARCHER_COMMIT_INTERVAL_MS:500}
        replication.factor: ${ARCHER_REPLICATION_FACTOR:1}
        max.poll.interval.ms: 300000
        max.poll.records: 500
        session.timeout.ms: 10000
        client.id: $UUID
        application.id: local-gateway-enrichment-group_replayer
        state.dir: /tmp/kafka-streams-XXX
        num.standby.replicas: 0
custom:
    topicName: default-gateway3
